name: todo-app

volumes:
  app-vol:
  db-vol:

networks:
  backend:
    name: backend
    driver: bridge

services:
  database:
    image: couchbase:community-7.6.1
    restart: on-failure
    container_name: database
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"
    volumes:
      - db-vol:/home/node/couchbase
    networks:
      - backend

  app:
    build: .
    image: todo-app:1.0
    restart: always
    container_name: app
    depends_on:
      - database
    environment:
      - COUCHBASE_HOST=database
    ports:
      - "8080:8080"
    volumes:
      - app-vol:/home/node/todo-app
    networks:
      - backend
